services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Example\Typo3ConsoleInProcessCommandTestCases\:
    resource: '../Classes/*'

  Example\Typo3ConsoleInProcessCommandTestCases\TestCommand:
    tags:
      - name: console.command
        command: "do-test"

