# Taken from https://github.com/TYPO3-Console/TYPO3-Console/blob/acf0a931ba9a985311430257de78a922c79f16cc/.github/workflows/Test.yml
name: Test

on: [ push, pull_request ]

defaults:
    run:
        shell: bash

jobs:
    Tests:
        name: 'T3 ${{ matrix.typo3 }} - ${{ matrix.os }} - PHP ${{ matrix.php }}'
        runs-on: ${{ matrix.os }}
        timeout-minutes: 5

        strategy:
            fail-fast: false
            matrix:
                os: [ 'ubuntu-latest' ]
                typo3: [ '^11.5.26', '^12.4', '^13.4' ]
                php: [ 8.1, 8.2, 8.3, 8.4 ]
                exclude:
                    - typo3: "^11.5.26"
                      php: 8.4
                    - typo3: "^12.4" # Because of conflict with vimeo/psalm
                      php: 8.4
                    - typo3: "^13.4"
                      php: 8.1
                include:
                    -   os: 'windows-latest'
                        php: 8.4
                        typo3: '^13.4'

        steps:
            -   name: Start database server
                if: matrix.os == 'ubuntu-latest'
                run: sudo /etc/init.d/mysql start

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Composer Cache Vars
                id: composer-cache-vars
                run: |
                    echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
                    echo "timestamp=$(date +"%s")" >> $GITHUB_OUTPUT

            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache-vars.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.php }}-${{ steps.composer-cache-vars.outputs.timestamp }}
                    restore-keys: |
                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-${{ matrix.php }}-
                        ${{ runner.os }}-composer-${{ matrix.typo3 }}-
                        ${{ runner.os }}-composer-

            -   name: Set up PHP Version ${{ matrix.php }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: mbstring, intl, pdo_sqlite, pdo_mysql
                    tools: composer:v2
                    coverage: none

            -   name: Environment Check
                run: |
                    php --version
                    composer --version

            -   name: Install
                env:
                    COMPOSER_ROOT_VERSION: 0.1.0
                run: |
                    composer update --with "typo3/cms-core:${{ matrix.typo3 }}" --no-interaction

            -   name: Check PHP
                run: php vendor/bin/psalm

            -   name: Test Install (Unix)
                if: matrix.os == 'ubuntu-latest'
                env:
                    TYPO3_INSTALL_DB_DRIVER: mysqli
                    TYPO3_INSTALL_DB_USER: root
                    TYPO3_INSTALL_DB_PASSWORD: root
                    TYPO3_INSTALL_DB_HOST: localhost
                    TYPO3_INSTALL_DB_DBNAME: typo3_test_ci_github
                    TYPO3_INSTALL_ADMIN_USER: admin
                    TYPO3_INSTALL_ADMIN_PASSWORD: Password1!
                    TYPO3_INSTALL_SITE_NAME: ddev site
                    TYPO3_INSTALL_SITE_SETUP_TYPE: none
                    TYPO3_INSTALL_SITE_BASE_URL: /
                    TYPO3_INSTALL_WEB_SERVER_CONFIG: none
                run: php vendor/bin/typo3 install:setup --force --no-interaction -vvv

            -   name: Test Install (Windows)
                if: matrix.os == 'windows-latest'
                env:
                    TYPO3_INSTALL_DB_DRIVER: pdo_sqlite
                    TYPO3_INSTALL_ADMIN_USER: admin
                    TYPO3_INSTALL_ADMIN_PASSWORD: Password1!
                    TYPO3_INSTALL_SITE_NAME: ddev site
                    TYPO3_INSTALL_SITE_SETUP_TYPE: none
                    TYPO3_INSTALL_SITE_BASE_URL: /
                    TYPO3_INSTALL_WEB_SERVER_CONFIG: none
                run: php vendor/bin/typo3 install:setup --force --no-interaction -vvv

            -   name: Test
                if: matrix.os == 'ubuntu-latest'
                run: php vendor/bin/typo3 do-test

            -   name: Test - Windows
                if: matrix.os == 'windows-latest'
                run: php vendor/bin/typo3 do-test

